trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnectionId: 'BillTestServiceConnection'
  webAppName: 'Bill-UI-Test'  # Replace with your actual Angular app name
  nodeVersion: '20.x'
  angularCliVersion: '18.0.3'  # Use the latest Angular version

jobs:
  - job: BuildJob
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '$(nodeVersion)'
          displayName: 'Install Node.js'

      - script: npm install -g @angular/cli@$(angularCliVersion)
        displayName: 'Install Angular CLI'

      - script: |
          npm install
          ng build --configuration production
        displayName: 'Build Angular app'

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

